import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../features/auth/AuthProvider";
import { Toaster } from "sonner";
import { Sidebar } from "../components/Sidebar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pt-BR" className={`${inter.variable} h-full antialiased`}>
      <body>
        <AuthProvider>
          <div className="flex">
            <Sidebar />
            <main className="bg-gray-50 ml-56 w-full p-8">{children}</main>
          </div>

          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
